//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSystemMvc.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbMvcSchoolEntities : DbContext
    {
        public DbMvcSchoolEntities()
            : base("name=DbMvcSchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Clubs> Tbl_Clubs { get; set; }
        public virtual DbSet<Tbl_Lessons> Tbl_Lessons { get; set; }
        public virtual DbSet<Tbl_Notes> Tbl_Notes { get; set; }
        public virtual DbSet<Tbl_Students> Tbl_Students { get; set; }
    }
}
