//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSystemMvc.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Notes
    {
        public int NoteID { get; set; }
        public Nullable<byte> LessonID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<byte> Exam1 { get; set; }
        public Nullable<byte> Exam2 { get; set; }
        public Nullable<byte> Exam3 { get; set; }
        public Nullable<byte> Project { get; set; }
        public Nullable<decimal> Avarage { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Tbl_Lessons Tbl_Lessons { get; set; }
        public virtual Tbl_Students Tbl_Students { get; set; }
    }
}
